version: '3'
services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3030:8080
  web:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 3031:80
    depends_on:
      - server 